apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue-v1
  namespace: product-catalogue-v1
  labels:
    app: product-catalogue
    version: v1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalogue
      version: v1.0
  template:
    metadata:
      labels:
        app: product-catalogue
        version: v1.0
    spec:
      containers:
      - name: product-catalogue
        image: krishna2302/moonrider-prod:IMAGE_TAG
        ports:
        - containerPort: 9191
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/javatechie"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: SERVER_PORT
          value: "9191"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9191
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9191
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 9191
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-v1-service
  namespace: product-catalogue-v1
spec:
  selector:
    app: product-catalogue
    version: v1.0
  ports:
  - port: 80
    targetPort: 9191
    protocol: TCP
  type: ClusterIP