name: CI/CD Pipeline
on:
  push:
    branches: [main]

env:
  IMAGE_NAME: krishna2302/moonrider-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set image tag
      id: set-tag
      run: |
        SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-8)
        echo "tag=$SHORT_SHA" >> "$GITHUB_OUTPUT"

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.tag }}
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}

  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
      
      - name: Load Docker image to Kind
        run: |
          docker pull krishna2302/moonrider-prod:${{ needs.build-and-push.outputs.image-tag }}
          kind load docker-image krishna2302/moonrider-prod:${{ needs.build-and-push.outputs.image-tag }} --name prod

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          sed "s|IMAGE_TAG|${{ needs.build-and-push.outputs.image-tag }}|g" k8s/deployment.yaml | kubectl apply -f -
          kubectl apply -f k8s/


      - name: Wait for Deployment
        run: |
          echo "Waiting for pod to be ready...."
          kubectl rollout status deployment/product-catalogue-v1 -n product-catalogue-v1

      - name: Verify Deployment
        run: |
          echo " --- Deployment Verification --- "
          echo " Namespaces: "
          kubectl get namespaces

          echo "\n Pods in all namespaces: "
          kubectl get pods --all-namespaces -o wide
          
          echo "\n Services in all namespaces: "
          kubectl get services --all-namespaces

          echo "\n Ingress Status: "
          kubectl get ingress --all-namespaces

          echo "\n HPA Status: "
          kubectl get hpa --all-namespaces
